[tool.poetry]
name = "app"
version = "0.1.0"
description = "An app that aggregates FastQC, FastP and HybPiper"
authors = ["Daniel Marchena Parreira <danielmapar@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
fast-app = "app.main:main"

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
dotenv = "^0.9.9"
requests = "^2.32.4"
pillow = "^11.3.0"
psutil = "^7.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pyinstaller = "^6.14.1"
types-requests = "^2.32.4.20250611"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
