name: Build and Release FastApp

on:
  push:
    branches: [ main, dev ]
    tags: [ 'v*' ]
  # pull_request:
  #   branches: [ main, dev ]

permissions:
  contents: write

jobs:
  build-app:
    uses: ./.github/workflows/build-workflow.yml
    with:
      os-matrix: '["ubuntu-latest"]'
      python-version: '3.13'
      poetry-version: '1.8.4'
      app-name: 'FastApp'
      working-directory: './app'
      build-windowed: true
        
  release-app:
    needs: build-app
    uses: ./.github/workflows/release-workflow.yml
    with:
      app-name: 'FastApp'
      tag-prefix: 'v'
      prerelease: true
      release-title-prefix: 'FastApp'
      artifact-patterns: |
        ./**/FastApp*
      generate-release-notes: true