name: Build Workflow

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.13'
      poetry-version:
        description: 'Poetry version to use'
        required: false
        type: string
        default: '1.8.4'
      app-name:
        description: 'Name of the application'
        required: false
        type: string
        default: 'FastApp'
      working-directory:
        description: 'Working directory for the app'
        required: false
        type: string
        default: './app'


jobs:
  build-app:
    runs-on: ${{ inputs.runner }}
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install pipx
      run: |
        sudo apt update
        sudo apt install -y pipx
    
    - name: Create .env file based on env_sample file
      run: |
        cp ${{ inputs.working-directory }}/.env_sample ${{ inputs.working-directory }}/.env
        
    - name: Install Poetry ${{ inputs.poetry-version }}
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
        
    - name: Configure Poetry to use Python ${{ inputs.python-version }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry env use python${{ inputs.python-version }}
        
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry install
        
    - name: Build executable
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry run pyinstaller --clean FastApp.spec
        
    - name: Prepare artifact name
      id: artifact-name
      shell: bash
      run: |
        echo "artifact=${{ inputs.app-name }}-linux" >> $GITHUB_OUTPUT
        echo "binary=${{ inputs.app-name }}" >> $GITHUB_OUTPUT
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-name.outputs.artifact }}
        path: ${{ inputs.working-directory }}/dist/${{ steps.artifact-name.outputs.binary }} 